apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: database-
spec:
  serviceAccountName: db-build-bot
  params:
  - name: app-name
    value: postgresql
  - name: source-repo
    value: https://github.com/davidbieder/fullstack-database
  pipelineRef:
    name: database
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce
  - name: gitops-repository
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
  - name: git-credentials
    secret:
      secretName: git-credentials