apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: postgresql
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/david-bieder-postgresql/postgresql
