apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-build-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
roleRef:
  name: deployer
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: db-build-bot
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
rules:
  - resources:
      - deployments
    apiGroups:
      - apps
    verbs:
      - get
      - create
      - list
      - patch
      - watch
  - resources:
      - services
    apiGroups:
      - ""
    verbs:
      - get
      - patch
      - create
  - resources:
      - imagestreams
    apiGroups:
      - "image.openshift.io"
    verbs:
      - get
      - patch
      - create