apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: database
spec:
  params:
  - name: app-name
    type: string
    description: Application name
  - name: source-repo
    type: string
    description: Source code repository
  - name: sha
    type: string
    description: Precise SHA of the commit to build
    default: ""
  tasks:
  - name: clone-repository
    params:
    - name: url
      value: "$(params.source-repo)"
    - name: revision
      value: "$(params.sha)"
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: pipeline-shared-data
  - name: create-configuration
    params:
    - name: app-name
      value: "$(params.app-name)"
    - name: commit
      value: "$(tasks.clone-repository.results.commit)"
    - name: source-repo
      value: "$(params.source-repo)"
    runAfter:
    - clone-repository
    taskRef:
      name: db-create-configuration
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  - name: deploy
    params:
    - name: app-namespace
      value: "$(context.pipelineRun.namespace)"
    - name: manifest
      value: "$(tasks.create-configuration.results.manifest)"
    runAfter:
    - create-configuration
    taskRef:
      name: deploy
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  - name: save-configuration
    params:
    - name: manifest
      value: "$(tasks.create-configuration.results.manifest)"
    - name: app-name
      value: "$(params.app-name)"
    - name: sha
      value: "$(tasks.clone-repository.results.commit)"
    runAfter:
    - deploy
    taskRef:
      name: save-configuration
    workspaces:
    - name: source
      workspace: pipeline-shared-data
    - name: target
      workspace: gitops-repository
    - name: git-credentials
      workspace: git-credentials
  workspaces:
  - name: pipeline-shared-data
  - name: gitops-repository
  - name: git-credentials
