apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: db-webhook-receiver
spec:
  port:
    targetPort: 8080
  to:
    name: el-db-webhook-receiver
    kind: Service
    weight: 100
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: db-webhook-receiver
spec:
  serviceAccountName: db-webhook-receiver
  triggers:
    - template:
        name: db-webhook-receiver
      bindings:
        - ref: db-webhook-receiver
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: db-webhook-receiver
spec:
  params:
    - name: source-repo
      value: $(body.repository.url)
    - name: sha
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: db-webhook-receiver
spec:
  params:
    - name: source-repo
      description: Source code repository
    - name: sha
      description: Precise SHA of the commit to build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: database-
      spec:
        serviceAccountName: db-build-bot
        params:
          - name: app-name
            value: postgresql
          - name: source-repo
            value: $(tt.params.source-repo)
          - name: sha
            value: $(tt.params.sha)
        pipelineRef:
          name: database
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
                accessModes:
                  - ReadWriteOnce
          - name: gitops-repository
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
                accessModes:
                  - ReadWriteOnce
          - name: git-credentials
            secret:
              secretName: git-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-webhook-receiver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-webhook-receiver
roleRef:
  name: db-webhook-receiver
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: db-webhook-receiver
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-webhook-receiver
rules:
  - resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    apiGroups:
      - triggers.tekton.dev
    verbs:
      - get
  - resources:
      - pipelineruns
      - pipelineresources
    apiGroups:
      - tekton.dev
    verbs:
      - create
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - list